apiVersion: batch/v1
kind: Job
metadata:
  name: intavia-job
spec:
  template:
    spec:
      containers:
      - name: intavia-flow
        env:
          - name: RDFDB_USER
            valueFrom:
              secretKeyRef:
                name: intavia-platform-secrets
                key: workflow_rdfdb_user
          - name: RDFDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: intavia-platform-secrets
                key: workflow_rdfdb_password
          - name: ZENODO_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: intavia-platform-secrets
                key: workflow_zenodo_api_token
          - name: GITHUB_USERNAME
            valueFrom:
              secretKeyRef:
                name: intavia-platform-secrets
                key: workflow_github_username 
          - name: GITHUB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: intavia-platform-secrets
                key: workflow_github_password
        volumeMounts:
        - name: prefect-archive
          mountPath: /archive
      volumes:
        - name: prefect-archive
          persistentVolumeClaim:
            claimName: prefect-archive-2
